### ISSUE TITLE
value_threshold not taken into account

### ISSUE THREAD

**Issue by bguillod** [davidnbresch/climada_module_country_risk#1]
The parameters "value_threshold" in "climada_centroids_generate_blackmarble_entity" is not used in the code. Instead, it seems that all centroids with value 0 are removed from the blackmarble entity in all cases. It would be nice to avoid this behaviour (as in the code documentation, which states that "if empty or =0, all centroids are kept in the entity (default)".

**Comment by ThomasRoosli** [comment]
Hi
Thanks for bringing that to my attention. The function was not behaving like described in the function head indeed. I just pushed a fix. Please confirm, if now the function
is behaving as desired.

**Comment by bguillod** [comment]
Hi Thomas, yes I confirm that now it looks like it's going what it's supposed to. Many thanks for fixing this quickly.

**Comment by bguillod** [comment]
Although I should add a proposed change to line 323:
        selection_is_positive = value_centroids >= parameters.value_threshold;
Since the documentation says "if empty or =0 ...", which suggests that only values equal to the threshold are also kept in. In case it is empty it works either way though.

**Comment by ThomasRoosli** [comment]
Good point it still does not match, I would rather suggest to update the text in the description. If we change the line 323 as you suggested, there would be no more option to only keep nonzero elements (fairly: there would be with realmin('double') but that is complicated).

**Comment by bguillod** [comment]
Good point and your solution sounds good to me.

**Comment by ThomasRoosli** [comment]
fix pushed.

**Comment by davidnbresch** [comment]
nice to see conversations like this - and so swiftly handled!

Prof. Dr. David N. Bresch 
Professor for Weather and Climate Risks
Institute for Environmental Decisions
ETH Zurich/MeteoSwiss
dbresch@ethz.ch <mailto:dbresch@ethz.ch>, dbresch@meteoswiss.ch <mailto:dbresch@meteoswiss.ch>
office: +41 44 632 77 87
mobile: +41 79 770 15 92
skype: davidnbresch
www.usys.ethz.ch/en/people/profile.html?persid=49820 <http://www.usys.ethz.ch/en/people/profile.html?persid=49820>, http://www.wcr.ethz.ch <http://www.wcr.ethz.ch/>
